export CUDA_VISIBLE_DEVICES=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/electricity/ \
    --data_path electricity.csv \
    --model_id electricity_96 \
    --model UniMixer \
    --data custom \
    --features M \
    --seq_len 96 \
    --pred_len 96 \
    --batch_size 128 \
    --learning_rate 5e-4 \
    --enc_in 321 \
    --dec_in 321 \
    --c_out 321 \
    --des 'Exp' \
    --d_model 32 \
    --n_heads 8 \
    --d_ff 128 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 50 \
    --patience 3 \
    --e_layers 3 \
    --k 4
    
python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/electricity/ \
    --data_path electricity.csv \
    --model_id electricity_192 \
    --model UniMixer \
    --data custom \
    --features M \
    --seq_len 96 \
    --pred_len 192 \
    --batch_size 128 \
    --learning_rate 5e-4 \
    --enc_in 321 \
    --dec_in 321 \
    --c_out 321 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 4 \
    --d_ff 64 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 50 \
    --patience 3 \
    --e_layers 3 \
    --k 1

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/electricity/ \
    --data_path electricity.csv \
    --model_id electricity_336 \
    --model UniMixer \
    --data custom \
    --features M \
    --seq_len 96 \
    --pred_len 336 \
    --batch_size 128 \
    --learning_rate 5e-4 \
    --enc_in 321 \
    --dec_in 321 \
    --c_out 321 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 8 \
    --d_ff 128 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 50 \
    --patience 3 \
    --e_layers 3 \
    --k 1

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/electricity/ \
    --data_path electricity.csv \
    --model_id electricity_720 \
    --model UniMixer \
    --data custom \
    --features M \
    --seq_len 96 \
    --pred_len 720 \
    --batch_size 128 \
    --learning_rate 5e-4 \
    --enc_in 321 \
    --dec_in 321 \
    --c_out 321 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 8 \
    --d_ff 128 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 50 \
    --patience 3 \
    --e_layers 3 \
    --k 1