export CUDA_VISIBLE_DEVICES=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/ETT-small/ \
    --data_path ETTm2.csv \
    --model_id ETTm2_96 \
    --model UniMixer \
    --data ETTm2 \
    --features M \
    --seq_len 96 \
    --pred_len 96 \
    --batch_size 128 \
    --learning_rate 1e-4 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 4 \
    --d_ff 64 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 10 \
    --patience 3 \
    --k 1

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/ETT-small/ \
    --data_path ETTm2.csv \
    --model_id ETTm2_192 \
    --model UniMixer \
    --data ETTm2 \
    --features M \
    --seq_len 96 \
    --pred_len 192 \
    --batch_size 128 \
    --learning_rate 1e-4 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 8 \
    --d_ff 32 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 10 \
    --patience 3 \
    --k 1

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/ETT-small/ \
    --data_path ETTm2.csv \
    --model_id ETTm2_336 \
    --model UniMixer \
    --data ETTm2 \
    --features M \
    --seq_len 96 \
    --pred_len 336 \
    --batch_size 128 \
    --learning_rate 1e-4 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --des 'Exp' \
    --d_model 32 \
    --n_heads 4 \
    --d_ff 64 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 10 \
    --patience 3 \
    --k 1

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/ETT-small/ \
    --data_path ETTm2.csv \
    --model_id ETTm2_720 \
    --model UniMixer \
    --data ETTm2 \
    --features M \
    --seq_len 96 \
    --pred_len 720 \
    --batch_size 128 \
    --learning_rate 5e-5 \
    --enc_in 7 \
    --dec_in 7 \
    --c_out 7 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 2 \
    --d_ff 64 \
    --dropout 0.1 \
    --head_dropout 0.1 \
    --fc_dropout 0.0 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 10 \
    --patience 3 \
    --k 1