export CUDA_VISIBLE_DEVICES=1
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id exchange_96 \
    --model UniMixer \
    --data custom \
    --features M \
    --seq_len 96 \
    --pred_len 96 \
    --batch_size 128 \
    --learning_rate 1e-4 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 2 \
    --d_ff 256 \
    --dropout 0.0 \
    --itr 1 \
    --lradj type4 \
    --train_epoch 6 \
    --patience 6 \
    --e_layers 2

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id exchange_192 \
    --model UniMixer \
    --data custom \
    --features M \
    --seq_len 96 \
    --pred_len 192 \
    --batch_size 128 \
    --learning_rate 1e-4 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --d_model 32 \
    --n_heads 2 \
    --d_ff 128 \
    --dropout 0.3 \
    --itr 1 \
    --lradj type4 \
    --train_epoch 4 \
    --patience 6 \
    --e_layers 2

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id exchange_336 \
    --model UniMixer \
    --data custom \
    --features M \
    --seq_len 96 \
    --pred_len 336 \
    --batch_size 128 \
    --learning_rate 1e-4 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 2 \
    --d_ff 128 \
    --dropout 0.3 \
    --itr 1 \
    --lradj type4 \
    --train_epoch 3 \
    --patience 6 \
    --e_layers 2

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/exchange_rate/ \
    --data_path exchange_rate.csv \
    --model_id exchange_720 \
    --model UniMixer \
    --data custom \
    --features M \
    --seq_len 96 \
    --pred_len 720 \
    --batch_size 128 \
    --learning_rate 1e-4 \
    --enc_in 8 \
    --dec_in 8 \
    --c_out 8 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 2 \
    --d_ff 128 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type4 \
    --train_epoch 4 \
    --patience 6 \
    --e_layers 3