export CUDA_VISIBLE_DEVICES=0
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/solar/ \
    --data_path solar_AL.txt \
    --model_id solar_96 \
    --model UniMixer \
    --data Solar \
    --features M \
    --seq_len 96 \
    --pred_len 96 \
    --batch_size 128 \
    --learning_rate 5e-4 \
    --enc_in 137 \
    --dec_in 137 \
    --c_out 137 \
    --des 'Exp' \
    --d_model 32 \
    --n_heads 8 \
    --d_ff 128 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type3 \
    --train_epoch 50 \
    --patience 6 \
    --e_layers 3

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/solar/ \
    --data_path solar_AL.txt \
    --model_id solar_192 \
    --model UniMixer \
    --data Solar \
    --features M \
    --seq_len 96 \
    --pred_len 192 \
    --batch_size 128 \
    --learning_rate 5e-4 \
    --enc_in 137 \
    --dec_in 137 \
    --c_out 137 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 8 \
    --d_ff 128 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type4 \
    --train_epoch 50 \
    --patience 3 \
    --e_layers 2 \
    --k 16

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/solar/ \
    --data_path solar_AL.txt \
    --model_id solar_336 \
    --model UniMixer \
    --data Solar \
    --features M \
    --seq_len 96 \
    --pred_len 336 \
    --batch_size 128 \
    --learning_rate 5e-4 \
    --enc_in 137 \
    --dec_in 137 \
    --c_out 137 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 8 \
    --d_ff 128 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type4 \
    --train_epoch 50 \
    --patience 6 \
    --e_layers 2 \
    --k 32

python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path dataset/solar/ \
    --data_path solar_AL.txt \
    --model_id solar_720 \
    --model UniMixer \
    --data Solar \
    --features M \
    --seq_len 96 \
    --pred_len 720 \
    --batch_size 128 \
    --learning_rate 5e-4 \
    --enc_in 137 \
    --dec_in 137 \
    --c_out 137 \
    --des 'Exp' \
    --d_model 16 \
    --n_heads 8 \
    --d_ff 128 \
    --dropout 0.1 \
    --itr 1 \
    --lradj type4 \
    --train_epoch 50 \
    --patience 3 \
    --e_layers 2 \
    --k 32